enum State {
    'Arizona'= 'AZ',
    'Alabama'= 'AL',
    'Alaska'= 'AK',
    'Arkansas'= 'AR',
    'California'= 'CA',
    'Colorado'= 'CO',
    'Connecticut'= 'CT',
    'District of Columbia'= 'DC',
    'Delaware'= 'DE',
    'Florida'= 'FL',
    'Georgia'= 'GA',
    'Hawaii'= 'HI',
    'Idaho'= 'ID',
    'Illinois'= 'IL',
    'Indiana'= 'IN',
    'Iowa'= 'IA',
    'Kansas'= 'KS',
    'Kentucky'= 'KY',
    'Louisiana'= 'LA',
    'Maine'= 'ME',
    'Maryland'= 'MD',
    'Massachusetts'= 'MA',
    'Michigan'= 'MI',
    'Minnesota'= 'MN',
    'Mississippi'= 'MS',
    'Missouri'= 'MO',
    'Montana'= 'MT',
    'Nebraska'= 'NE',
    'Nevada'= 'NV',
    'New Hampshire'= 'NH',
    'New Jersey'= 'NJ',
    'New Mexico'= 'NM',
    'New York'= 'NY',
    'North Carolina'= 'NC',
    'North Dakota'= 'ND',
    'Ohio'= 'OH',
    'Oklahoma'= 'OK',
    'Oregon'= 'OR',
    'Pennsylvania'= 'PA',
    'Rhode Island'= 'RI',
    'South Carolina'= 'SC',
    'South Dakota'= 'SD',
    'Tennessee'= 'TN',
    'Texas'= 'TX',
    'Utah'= 'UT',
    'Vermont'= 'VT',
    'Virginia'= 'VA',
    'Washington'= 'WA',
    'West Virginia'= 'WV',
    'Wisconsin'= 'WI',
    'Wyoming'= 'WY',
    'American Samoa'= 'AS',
    'Guam'= 'GU',
    'Northern Mariana Islands'= 'MP',
    'Puerto Rico'= 'PR',
    'U.S. Virgin Islands'= 'VI',
    'U.S. Minor Outlying Islands'= 'UM',
}

export {}
// export const convertStateNameToAbbrev = (name: String) => State[name] ?? null
export const convertStateNameToAbbrev = (name: String) => {
    let a = name.trim().replace(/[^\w ]/g, "").toLowerCase(); //Trim, remove all non-word characters with the exception of spaces, and convert to lowercase
    // TODO: fix this    
    // if(State[a] !== null) {
    //         return State[a]
    //     }
    
        return null
}

/*

const State = {
    'Arizona': 'AZ',
    'Alabama': 'AL',
    'Alaska': 'AK',
    'Arkansas': 'AR',
    'California': 'CA',
    'Colorado': 'CO',
    'Connecticut': 'CT',
    'District of Columbia': 'DC',
    'Delaware': 'DE',
    'Florida': 'FL',
    'Georgia': 'GA',
    'Hawaii': 'HI',
    'Idaho': 'ID',
    'Illinois': 'IL',
    'Indiana': 'IN',
    'Iowa': 'IA',
    'Kansas': 'KS',
    'Kentucky': 'KY',
    'Louisiana': 'LA',
    'Maine': 'ME',
    'Maryland': 'MD',
    'Massachusetts': 'MA',
    'Michigan': 'MI',
    'Minnesota': 'MN',
    'Mississippi': 'MS',
    'Missouri': 'MO',
    'Montana': 'MT',
    'Nebraska': 'NE',
    'Nevada': 'NV',
    'New Hampshire': 'NH',
    'New Jersey': 'NJ',
    'New Mexico': 'NM',
    'New York': 'NY',
    'North Carolina': 'NC',
    'North Dakota': 'ND',
    'Ohio': 'OH',
    'Oklahoma': 'OK',
    'Oregon': 'OR',
    'Pennsylvania': 'PA',
    'Rhode Island': 'RI',
    'South Carolina': 'SC',
    'South Dakota': 'SD',
    'Tennessee': 'TN',
    'Texas': 'TX',
    'Utah': 'UT',
    'Vermont': 'VT',
    'Virginia': 'VA',
    'Washington': 'WA',
    'West Virginia': 'WV',
    'Wisconsin': 'WI',
    'Wyoming': 'WY',
    'American Samoa': 'AS',
    'Guam': 'GU',
    'Northern Mariana Islands': 'MP',
    'Puerto Rico': 'PR',
    'U.S. Virgin Islands': 'VI',
    'U.S. Minor Outlying Islands': 'UM',
}

*/
